// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySQL.Data;

#nullable disable

namespace MySQL.Migrations
{
    [DbContext(typeof(GyakorloDbContext))]
    partial class GyakorloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("MySQL.Model.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AjanloId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ajanlo_id");

                    b.Property<string>("CegesEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ceges_email");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nev")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nev");

                    b.Property<string>("Varos")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("varos");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("felhasznalok");
                });

            modelBuilder.Entity("MySQL.Model.Honap", b =>
                {
                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<string>("HonapNeve")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("honap_neve")
                        .HasDefaultValueSql("''");

                    b.Property<string>("HonapSzama")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("honap_szama");

                    b.ToTable((string)null);

                    b.ToView("honapok", (string)null);
                });

            modelBuilder.Entity("MySQL.Model.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nev")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nev");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("kategoria");
                });

            modelBuilder.Entity("MySQL.Model.NagykerAr", b =>
                {
                    b.Property<decimal?>("Ar")
                        .HasPrecision(12, 1)
                        .HasColumnType("TEXT")
                        .HasColumnName("ar");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("TermekNev")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("termek_nev");

                    b.ToTable((string)null);

                    b.ToView("nagyker_arak", (string)null);
                });

            modelBuilder.Entity("MySQL.Model.NoveltAr", b =>
                {
                    b.Property<decimal?>("Ar")
                        .HasPrecision(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("ar");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("TermekNev")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("termek_nev");

                    b.ToTable((string)null);

                    b.ToView("novelt_arak", (string)null);
                });

            modelBuilder.Entity("MySQL.Model.Rendeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<int?>("FelhasznaloId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("felhasznalo_id");

                    b.Property<decimal?>("Osszesen")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("osszesen");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("rendelesek");
                });

            modelBuilder.Entity("MySQL.Model.RendelesTetel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("Mennyiseg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mennyiseg");

                    b.Property<int?>("RendelesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rendeles_id");

                    b.Property<int?>("TermekId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("termek_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("RendelesId");

                    b.HasIndex("TermekId");

                    b.ToTable("rendeles_tetelek");
                });

            modelBuilder.Entity("MySQL.Model.TargyiEszkoz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Megnevezes")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("megnevezes");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("eszkozok");
                });

            modelBuilder.Entity("MySQL.Model.Termek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("Ar")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ar");

                    b.Property<int?>("KategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kategoria_id");

                    b.Property<string>("TermekNev")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("termek_nev");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("termekek");
                });

            modelBuilder.Entity("MySQL.Model.RendelesTetel", b =>
                {
                    b.HasOne("MySQL.Model.Rendeles", "Rendeles")
                        .WithMany("Tetelek")
                        .HasForeignKey("RendelesId");

                    b.HasOne("MySQL.Model.Termek", "Termek")
                        .WithMany()
                        .HasForeignKey("TermekId");

                    b.Navigation("Rendeles");

                    b.Navigation("Termek");
                });

            modelBuilder.Entity("MySQL.Model.Rendeles", b =>
                {
                    b.Navigation("Tetelek");
                });
#pragma warning restore 612, 618
        }
    }
}
